import { QRCodeSVG } from 'qrcode.react';
import { useRef } from 'react';

/**
 * Reusable QR Code Card Component
 * 
 * Drop this into any React project. Just pass a `value` prop.
 * 
 * Props:
 *   - value (string, required): The data/URL to encode in the QR
 *   - title (string): Header text above the QR
 *   - subtitle (string): Subtext below the title
 *   - size (number): QR code size in px (default: 200)
 *   - showDownload (bool): Show download button (default: true)
 *   - studentName (string): Student name for the filename
 */
const QRCodeCard = ({
    value,
    title = 'Your QR Code',
    subtitle = 'Scan this code to check attendance',
    size = 200,
    showDownload = true,
    studentName = 'student',
}) => {
    const qrRef = useRef(null);

    const handleDownload = () => {
        const svg = qrRef.current?.querySelector('svg');
        if (!svg) return;

        const svgData = new XMLSerializer().serializeToString(svg);
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        const img = new Image();

        img.onload = () => {
            canvas.width = img.width;
            canvas.height = img.height;
            ctx.fillStyle = '#ffffff';
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            ctx.drawImage(img, 0, 0);

            const link = document.createElement('a');
            link.download = `QR_${studentName.replace(/\s+/g, '_')}.png`;
            link.href = canvas.toDataURL('image/png');
            link.click();
        };
        img.src = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(svgData)));
    };

    const handlePrint = () => {
        const svg = qrRef.current?.querySelector('svg');
        if (!svg) return;

        const svgData = new XMLSerializer().serializeToString(svg);
        const win = window.open('', '_blank');
        win.document.write(`
            <html>
            <head><title>QR Code — ${studentName}</title></head>
            <body style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif;">
                <h2 style="margin-bottom:8px;">${studentName}</h2>
                <p style="color:#666;margin-bottom:24px;">${subtitle}</p>
                ${svgData}
                <p style="margin-top:16px;font-size:12px;color:#999;">Generated by AdmissionPortal</p>
            </body>
            </html>
        `);
        win.document.close();
        win.focus();
        win.print();
    };

    return (
        <div className="qr-card">
            <h3 className="qr-card-title">{title}</h3>
            <p className="qr-card-subtitle">{subtitle}</p>
            <div className="qr-code-wrapper" ref={qrRef}>
                <QRCodeSVG
                    value={value}
                    size={size}
                    level="H"
                    includeMargin={true}
                    bgColor="#ffffff"
                    fgColor="#1e3a5f"
                />
            </div>
            {showDownload && (
                <div className="qr-actions">
                    <button className="btn btn-primary qr-action-btn" onClick={handleDownload}>
                        📥 Download QR
                    </button>
                    <button className="btn btn-secondary qr-action-btn" onClick={handlePrint}>
                        🖨️ Print
                    </button>
                </div>
            )}
        </div>
    );
};

export default QRCodeCard;
